/**
 * Feature: social-commerce-guest-booking, Property 14: Data Minimisation in Social Messages
 *
 * For any outbound social channel message generated by a Channel_Adapter and for any
 * Social_Booking_Session document, the content SHALL NOT contain medical information,
 * allergy details, emergency contact details, payment card information, customer email
 * addresses, customer phone numbers, or customer full names (only first name or platform
 * display name is permitted).
 *
 * Validates: Requirements 10.1, 10.3, 10.5, 10.7, 16.3, 16.4
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fc from 'fast-check';
import { WhatsAppAdapter } from '@/lib/social-booking/adapters/whatsapp';
import { arbSessionSummary, arbBookingConfirmation } from '../helpers/generators';

// ─── Sensitive data generators ───────────────────────────────────────────────

/** Generates realistic medical information strings */
const arbMedicalInfo: fc.Arbitrary<string> = fc.oneof(
  fc.constantFrom(
    'Patient has Type 2 diabetes requiring insulin',
    'Severe asthma, uses ventolin inhaler twice daily',
    'Diagnosed with ADHD, takes Ritalin 10mg',
    'Epilepsy controlled with Carbamazepine',
    'Anaphylaxis history, carries EpiPen',
    'Coeliac disease, strict gluten-free diet required',
    'Heart condition, avoid strenuous activity'
  ),
  fc.string({ unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz '.split('')), minLength: 10, maxLength: 40 }).map((s) => `Medical condition: ${s.trim()}`)
);

/** Generates allergy detail strings */
const arbAllergyDetails: fc.Arbitrary<string> = fc.oneof(
  fc.constantFrom(
    'Allergic to peanuts, tree nuts, and sesame',
    'Severe dairy allergy - anaphylactic',
    'Shellfish allergy, carries antihistamines',
    'Gluten intolerance, coeliac diagnosed 2019',
    'Egg allergy - avoid all egg products',
    'Soy allergy, check all labels carefully'
  ),
  fc.string({ unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz '.split('')), minLength: 10, maxLength: 40 }).map((s) => `Allergy details: ${s.trim()}`)
);

/** Generates emergency contact details */
const arbEmergencyContact: fc.Arbitrary<string> = fc.oneof(
  fc.constantFrom(
    'Emergency: Jane Smith 07911234567',
    'Contact: Dr. Robert Brown +447700900123',
    'ICE: Sarah Williams 020 7946 0958',
    'Next of kin: Michael Jones 07456789012'
  ),
  fc.tuple(
    fc.constantFrom('Jane', 'Robert', 'Sarah', 'Michael'),
    fc.constantFrom('Smith', 'Brown', 'Williams', 'Jones'),
    fc.string({ unit: fc.constantFrom(...'0123456789'.split('')), minLength: 11, maxLength: 11 })
  ).map(([first, last, phone]) => `Emergency contact: ${first} ${last} ${phone}`)
);

/** Generates payment card information */
const arbPaymentCard: fc.Arbitrary<string> = fc.oneof(
  fc.constantFrom(
    '4242424242424242',
    '5555555555554444',
    '378282246310005'
  ),
  fc.string({ unit: fc.constantFrom(...'0123456789'.split('')), minLength: 16, maxLength: 16 })
);

/** Generates email addresses */
const arbEmail: fc.Arbitrary<string> = fc.tuple(
  fc.string({ unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz0123456789'.split('')), minLength: 3, maxLength: 12 }),
  fc.constantFrom('gmail.com', 'hotmail.co.uk', 'yahoo.com', 'outlook.com', 'proton.me')
).map(([local, domain]) => `${local}@${domain}`);

/** Generates UK phone numbers (not the recipient WhatsApp number) */
const arbPhoneNumber: fc.Arbitrary<string> = fc.oneof(
  fc.constantFrom(
    '07911234567',
    '+447700900123',
    '020 7946 0958',
    '+44 7456 789012'
  ),
  fc.tuple(
    fc.constantFrom('079', '078', '077'),
    fc.string({ unit: fc.constantFrom(...'0123456789'.split('')), minLength: 8, maxLength: 8 })
  ).map(([prefix, digits]) => `${prefix}${digits}`)
);

/** Generates full names (first + last) that should NOT appear in messages */
const arbFullName: fc.Arbitrary<string> = fc.tuple(
  fc.constantFrom('John', 'Jane', 'Michael', 'Sarah', 'Robert', 'Emma', 'David', 'Lucy'),
  fc.constantFrom('Smith', 'Jones', 'Williams', 'Brown', 'Taylor', 'Wilson', 'Davies', 'Evans')
).map(([first, last]) => `${first} ${last}`);

// ─── Composite sensitive data structure ──────────────────────────────────────

interface SensitiveData {
  medicalInfo: string;
  allergyDetails: string;
  emergencyContact: string;
  paymentCard: string;
  email: string;
  phoneNumber: string;
  fullName: string;
}

const arbSensitiveData: fc.Arbitrary<SensitiveData> = fc.record({
  medicalInfo: arbMedicalInfo,
  allergyDetails: arbAllergyDetails,
  emergencyContact: arbEmergencyContact,
  paymentCard: arbPaymentCard,
  email: arbEmail,
  phoneNumber: arbPhoneNumber,
  fullName: arbFullName,
});

// ─── Test helpers ────────────────────────────────────────────────────────────

/**
 * Captures all fetch call bodies made by the adapter.
 * Returns an array of stringified message bodies sent to the WhatsApp API.
 */
function getCapturedMessageBodies(fetchMock: ReturnType<typeof vi.fn>): string[] {
  return fetchMock.mock.calls
    .map((call: unknown[]) => {
      const options = call[1] as RequestInit | undefined;
      return options?.body as string || '';
    })
    .filter(Boolean);
}

/**
 * Asserts that none of the sensitive data values appear in any captured message body.
 * Only checks the message content fields (text.body, interactive.body.text, etc.),
 * NOT the 'to' field which legitimately contains the recipient WhatsApp phone number.
 */
function assertNoSensitiveDataInMessages(
  messageBodies: string[],
  sensitiveData: SensitiveData
): void {
  for (const body of messageBodies) {
    const parsed = JSON.parse(body);
    // Extract message content only — exclude the 'to' field (recipient WhatsApp number)
    const contentParts: string[] = [];

    if (parsed.text?.body) {
      contentParts.push(parsed.text.body);
    }
    if (parsed.interactive?.body?.text) {
      contentParts.push(parsed.interactive.body.text);
    }
    if (parsed.interactive?.action) {
      contentParts.push(JSON.stringify(parsed.interactive.action));
    }

    const messageContent = contentParts.join(' ');

    // Medical info should not appear
    expect(messageContent).not.toContain(sensitiveData.medicalInfo);

    // Allergy details should not appear
    expect(messageContent).not.toContain(sensitiveData.allergyDetails);

    // Emergency contact should not appear
    expect(messageContent).not.toContain(sensitiveData.emergencyContact);

    // Payment card numbers should not appear
    expect(messageContent).not.toContain(sensitiveData.paymentCard);

    // Email addresses should not appear
    expect(messageContent).not.toContain(sensitiveData.email);

    // Phone numbers should not appear in message content
    expect(messageContent).not.toContain(sensitiveData.phoneNumber);

    // Full names should not appear (only first name or display name is permitted)
    expect(messageContent).not.toContain(sensitiveData.fullName);
  }
}

// ─── Property Tests ──────────────────────────────────────────────────────────

describe('Property 14: Data Minimisation in Social Messages', () => {
  let fetchMock: ReturnType<typeof vi.fn>;
  let adapter: WhatsAppAdapter;

  beforeEach(() => {
    fetchMock = vi.fn().mockResolvedValue({ ok: true, status: 200 });
    vi.stubGlobal('fetch', fetchMock);
    process.env.META_WHATSAPP_PHONE_NUMBER_ID = 'test-phone-id';
    process.env.META_WHATSAPP_ACCESS_TOKEN = 'test-access-token';
    adapter = new WhatsAppAdapter();
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
    delete process.env.META_WHATSAPP_PHONE_NUMBER_ID;
    delete process.env.META_WHATSAPP_ACCESS_TOKEN;
  });

  it('sendSessionList outbound messages do NOT contain sensitive data for any SessionSummary', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(arbSessionSummary, { minLength: 1, maxLength: 5 }),
        arbSensitiveData,
        async (sessions, sensitiveData) => {
          fetchMock.mockClear();

          // The recipient ID is a WhatsApp number — this is the only phone number allowed in the payload 'to' field
          const recipientId = '447911000000';

          await adapter.sendSessionList(recipientId, sessions);

          const bodies = getCapturedMessageBodies(fetchMock);
          expect(bodies.length).toBeGreaterThan(0);

          assertNoSensitiveDataInMessages(bodies, sensitiveData);
        }
      ),
      { numRuns: 20 }
    );
  });

  it('sendBookingConfirmation outbound messages do NOT contain sensitive data for any BookingConfirmation', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbBookingConfirmation,
        arbSensitiveData,
        async (confirmation, sensitiveData) => {
          fetchMock.mockClear();

          const recipientId = '447911000000';

          await adapter.sendBookingConfirmation(recipientId, confirmation);

          const bodies = getCapturedMessageBodies(fetchMock);
          expect(bodies.length).toBeGreaterThan(0);

          assertNoSensitiveDataInMessages(bodies, sensitiveData);
        }
      ),
      { numRuns: 20 }
    );
  });

  it('sendBookingConfirmation only includes className, date, startTime, venueName — no payment amount, full names, or medical info', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbBookingConfirmation,
        fc.integer({ min: 500, max: 10000 }),
        arbFullName,
        arbMedicalInfo,
        async (confirmation, paymentAmountPence, fullName, medicalInfo) => {
          fetchMock.mockClear();

          const recipientId = '447911000000';

          await adapter.sendBookingConfirmation(recipientId, confirmation);

          const bodies = getCapturedMessageBodies(fetchMock);
          expect(bodies.length).toBeGreaterThan(0);

          // Extract message content from the body
          const parsed = JSON.parse(bodies[0]);
          const messageText: string = parsed.text?.body || '';

          // MUST include allowed fields
          expect(messageText).toContain(confirmation.className);
          expect(messageText).toContain(confirmation.date);
          expect(messageText).toContain(confirmation.startTime);
          expect(messageText).toContain(confirmation.venueName);

          // MUST NOT include payment amount
          const formattedAmount = `£${(paymentAmountPence / 100).toFixed(2)}`;
          expect(messageText).not.toContain(formattedAmount);

          // MUST NOT include full name
          expect(messageText).not.toContain(fullName);

          // MUST NOT include medical info
          expect(messageText).not.toContain(medicalInfo);
        }
      ),
      { numRuns: 20 }
    );
  });
});
